"""fix tables

Revision ID: 16109813f504
Revises: 
Create Date: 2022-07-08 21:53:15.015690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16109813f504'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
