"""fix tables

Revision ID: 403f914f363c
Revises: 5962bc9b0934
Create Date: 2022-07-08 21:56:51.327909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403f914f363c'
down_revision = '5962bc9b0934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
