"""fix tables

Revision ID: b09382584ab2
Revises: 403f914f363c
Create Date: 2022-07-11 13:24:33.692823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b09382584ab2'
down_revision = '403f914f363c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
